### ISSUE TITLE
Include CSS classes for SVG map elements

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/gw-conditions#16]
Need to do this before #15

**Comment by collnell** [comment]
Currently implemented:
- [ ] country/state outlines to drive appearance 
- [ ] on path for each site_no with site_no used in naming to bind with imported data

Needed:
- to do a regional zoom we could use outlines of the focal regions with a related class or id, or state outlines with a class for region
- a class for whether a well is confined or unconfined? this could allow us to add a simple on/off for these two categories

**Comment by collnell** [comment]
Along with this, we can remove styling from the svg itself. svg > js > css, so if it's defined on the element it will override anything else

**Comment by lindsayplatt** [comment]
CSS classes for the additional interactivity elements have been noted in #19. This issue is complete otherwise.
