### ISSUE TITLE
Interactive viz version

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/gw-conditions#19]
Add interactivity through regional polygons that have zoom in/zoom out similar to the water use state zoom.

**Comment by collnell** [comment]
Should also consider a toggle for confined vs unconfined wells

**Comment by lindsayplatt** [comment]
Note that these interactivities could be helped by including additional CSS classes. See this comment https://github.com/USGS-VIZLAB/gw-conditions/issues/16#issuecomment-875792289
