### ISSUE TITLE
SVG has some `translate(NA NA)` which crashes Vue

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/gw-conditions#25]
https://github.com/USGS-VIZLAB/gw-conditions/pull/24#issuecomment-875175037

@collnell has a bandaid for this on their end.

**Comment by collnell** [comment]
I did some investigating. The sites that appear as NA are ones in Puerto Rico, Alaska, etc. We should definitely include these locations in the final product, so I expect this will self-resolve once they are added.

**Comment by ceenell** [comment]
This has been resolved with the addition of all U.S. states and territories
