### ISSUE TITLE
add PR, HI, AK to map

### ISSUE THREAD

**Issue by ceenell** [USGS-VIZLAB/gw-conditions#29]

**Comment by lindsayplatt** [comment]
Maybe this will help: https://github.com/USGS-VIZLAB/gage-conditions/blob/ae2e8a6481676e081a67349ed0333b060399bdcc/scripts/map_preprocess/geo_utils.R#L69-L76

**Comment by lindsayplatt** [comment]
Updating progress today. In my current fork, see this commit, the code appropriately shifts, scales, rotates, and adds our 6 regions that fall outside of our CONUS map. Running `scmake("src/assets/anomaly_peaks.svg")` and then looking at the SVG (and changing stroke to "black" not "white"), results the following:

![image](https://user-images.githubusercontent.com/13220910/146260088-f45f991e-2cee-4877-8acc-da8922826168.png)

Remaining work:

1. Figure out why my lines are being drawn & connected (though, worried it is a Lindsay computer problem as we discovered [here](https://github.com/USGS-VIZLAB/svg-maps/pull/1#issuecomment-976534959) and not a real problem)
2. Find higher resolution data for PR, VI, GU, and AS.
3. Add the peaks for these 5 regions

**Comment by lindsayplatt** [comment]
Other thoughts: where do we want American Samoa and Guam to be shifted on our map? I currently have them in the Gulf of Mexico, but maybe that isn't the best place. I need to go glance at other maps and see what other people do.

**Comment by ceenell** [comment]
Here is what the Drought monitor does: 
![image](https://user-images.githubusercontent.com/17803537/146263399-c14d66b7-9fe5-4a5f-a044-6e958db7331e.png)

Are the islands scaled to one another or on their own?

**Comment by lindsayplatt** [comment]
Each is scaled on their own

**Comment by ceenell** [comment]
I think the smaller islands need to be at a higher resolution than other shapes. They are so small that when they are getting scaled up they look distorted

**Comment by ceenell** [comment]
A few other layouts I see:

![image](https://user-images.githubusercontent.com/17803537/146271979-6ff57d1d-1c42-415b-b8f2-9b7e1f266d72.png)

![image](https://user-images.githubusercontent.com/17803537/146272344-552ca6ff-3d46-4760-8548-485eda55b5fa.png)

![image](https://user-images.githubusercontent.com/17803537/146272398-95da360b-6cd0-45c3-abe7-e032c735844c.png)

![image](https://user-images.githubusercontent.com/17803537/146272466-28b317c3-ee57-4d6d-8b67-6c6e04d04d3f.png)
![image](https://user-images.githubusercontent.com/17803537/146272557-f6ac95b1-4dad-433d-895d-0beed68046f4.png)
![image](https://user-images.githubusercontent.com/17803537/146272668-3f4b3991-dd20-477d-a488-d1f7666e283b.png)

**Comment by lindsayplatt** [comment]
> I think the smaller islands need to be at a higher resolution than other shapes. They are so small that when they are getting scaled up they look distorted

yep, totally agree! That is one of the 3 items in the remaining work I noted at the end of that first comment.

**Comment by lindsayplatt** [comment]
I kind of like that last layout the most (except will increase the size of VI, GU, and AS) because it puts them in locations more logical compared to their actual geographic locations relative to CONUS.

**Comment by hcorson-dosch** [comment]
Yes I agree re: each of the insets are scaled on their own and have their own centered projection -- I think that's already how Lindsay has it set up?

As for layouts, I personally like the Drought monitor or the first grey map that separate the insets from the main map visually with a box or line, so that it's clear that the direction and distance between the main map and the insets are not meant to be accurate, and that the scale differs between the main map and each of the insets.

**Comment by lindsayplatt** [comment]
We can play around with placement more, but I did incorporate higher-resolution data and shifted to match that last map. I like the drought monitor _except_ that it puts Hawaii and Alaska to the east of CONUS. 

Still have those stupid line connections, but please look past those when you view this :)
![image](https://user-images.githubusercontent.com/13220910/146286218-9fa24b4e-5459-46e2-930a-c4206d13577a.png)

**Comment by hcorson-dosch** [comment]
Agreed that it feels weird to have AK east of CONUS

**Comment by hcorson-dosch** [comment]
Also, I think we _could_ simplify AK and CONUS even more to get rid of more of that crunchiness along the coastlines, but I think it's also fine as is.

**Comment by lindsayplatt** [comment]
I've got the points shifting! There was a lot of math that happened this morning :)

With the current state of my branch, I can run this and the following map:

```r
library(sf)
library(dplyr)
source("3_visualize/src/sf_utils_shift.R")

albers <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
usa_sf <- maps::map("usa", fill = TRUE, plot=FALSE) %>%
  sf::st_as_sf() %>% 
  st_transform(albers) %>% 
  st_buffer(0) 
oconus_sf <- build_oconus_sf(proj_str = albers)
sites_sf <- scmake("gw_sites_sf_shifted")

par(mar = c(0,0,0,0))
plot(st_geometry(oconus_sf), col = "white", border = NA) # Get the margins set appropriately
plot(st_geometry(usa_sf), add=T, col="lightgrey", border = NA)
plot(st_geometry(oconus_sf), add=T, col="lightgrey", border = NA)
plot(st_geometry(sites_sf), add=T, pch=16, cex=0.5, col = "blue")
```

![image](https://user-images.githubusercontent.com/13220910/146599896-a02506d4-f2cd-4cc6-8fe2-05a752625590.png)
