### ISSUE TITLE
Get GW stats to use for first viz concept

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/gw-conditions#3]
Putting my findings here instead of building into the repo for now.

We would like to use GW stats to compare GW conditions to "normal" in our first viz idea. Where do we get these stats? For the [Climate Response Network sites](https://groundwaterwatch.usgs.gov/CRNHome.asp), we see that there are [stat tables on their GW pages](https://groundwaterwatch.usgs.gov/AWLSites.asp?mt=g&S=422849099521503&ncd=awl) (see screenshot below); however, we cannot find these in a service. There is the stat service which provides stats for some GW sites. You can see an example of how to pull different stat types for site `310428084310503` below (the first example is how to get the exact data seen at [this table](https://waterdata.usgs.gov/nwis/monthly?referred_module=sw&site_no=310428084310503&agency_cd=USGS&por_310428084310503_38053=864029,72019,38053,1980-02,2021-01&format=html_table)).

Stat table online for CRN sites:
![image](https://user-images.githubusercontent.com/13220910/105551040-d06d3f80-5cc7-11eb-80ab-548bf07060e9.png)

```r
library(dataRetrieval)
library(dplyr)

site_no <- "310428084310503"

# I can get the monthly stats: 
readNWISstat(site_no, "72019", statReportType = "monthly")

# I can get monthly means by running:
readNWISstat(site_no, "72019") %>% 
  group_by(month_nu) %>% 
  summarize(month_mean = mean(mean_va))

# I can get daily percentiles by running:
readNWISstat(site_no, "72019", statType = c("P10", "P25", "P75", "P90"))

# I can get monthly percentiles by running (CANNOT use statReportType = "monthly" bc
#   monthly and annual report types only provide means):
readNWISstat(site_no, "72019", statType = c("P10", "P25", "P75", "P90")) %>% 
  group_by(month_nu) %>% 
  summarize_at(vars(p10_va, p25_va, p75_va, p90_va), mean)
```

I then tried to see if any CRN sites had these stats, but none appear to.
```r
# Try to see if any of the CRN sites have stats:
library(scipiper)
gw_crn_sites <- scmake("gw_crn_sites")
crn_stats <- data.frame()

for(s in gw_crn_sites) {
  rbind(crn_stats, readNWISstat(s, "72019"))
}

# RESULTS
> crn_stats
data frame with 0 columns and 0 rows
```

**Comment by collnell** [comment]
This did work for me with one small edit: 
` crn_stats <- rbind(crn_stats, readNWISstat(s, "72019"))`

**Comment by collnell** [comment]
![image](https://user-images.githubusercontent.com/17803537/105553111-820d7000-5cca-11eb-95f9-aca6863a147e.png)

**Comment by lindsayplatt** [comment]
OMG DUH. THANK YOU!!!!!!!!!!!!

**Comment by lindsayplatt** [comment]
Ok, so that last part where we check stat stuff for CRN sites SHOULD look like this and we get stats back for 421 of the 675 sites.

```
library(scipiper)
library(dataRetrieval)
library(dplyr)

gw_crn_sites <- scmake("gw_crn_sites")
crn_stats <- data.frame()

for(s in gw_crn_sites) {
  crn_stats <- rbind(crn_stats, readNWISstat(s, "72019"))
}

crn_stats %>% 
  pull(site_no) %>% 
  unique() %>% 
  length()

[1] 421
```

**Comment by lindsayplatt** [comment]
Pivoting away from CRN sites, so closing
