### ISSUE TITLE
Add steps to push data used by D3/Vue from the pipeline

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/gw-conditions#41]
Now that #31 is resolved, @ceenell will list out those files they need here and then Lindsay will edit the pipeline.

**Comment by ceenell** [comment]
The following files are written to `public` and need to be pushed to s3 and stored under `data`:
- `gw-conditions-daily-proportions.csv'
- `gw-conditions-site-coords.csv`
- `gw-conditions-wy20.csv`
- `gw-conditions-time-labels.csv`

**Comment by lindsayplatt** [comment]
Figure out how to name `gw-conditions-wy20.csv` dynamically in the pipeline, so that we can keep previous years.

**Comment by lindsayplatt** [comment]
Taking this on now. @ceenell are these still the files we need? I think we are keeping the SVG as a file in this repo? Or should that go to S3, too?

**Comment by ceenell** [comment]
Yes, these are the files we use in vue. Go ahead and include the svg in that, I am still sorting out how to inject that from url but will address that this week
