### ISSUE TITLE
Label oconus

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/gw-conditions#49]
Need to make it clear that GU, AS, and MP are not part of AK. Explore options and then implement! Here is one example that @ceenell shared:

![image](https://user-images.githubusercontent.com/13220910/147122337-85cf05a1-f989-44a7-b1d6-77b23995c890.png)

**Comment by ceenell** [comment]
Mock-up of labelling by @hcorson-dosch
![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/17803537/147597640-33e2559a-45f4-44dc-abed-e7df1136ff3d.png)

**Comment by lindsayplatt** [comment]
Just missing Guam on beta right now but @ceenell has this fix locally already! Close this once it is up in the canonical repo.
